name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build the APK with Buildozer Action
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # where your buildozer.spec lives (repo root in your case)
          workdir: .
          # stable = PyPI release of buildozer; switch to 'master' if needed
          buildozer_version: stable
          # (optional) custom command e.g.:
          # command: buildozer -v android debug

      # Upload the produced APK/AAB automatically
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: scicalc-apk
          path: ${{ steps.buildozer.outputs.filename }}
