name: Build Android APK


on:
workflow_dispatch:
push:
branches: [ "main" ]


jobs:
build-apk:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Cache Buildozer & Gradle
uses: actions/cache@v4
with:
path: |
.buildozer
.gradle
key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
restore-keys: |
${{ runner.os }}-buildozer-


- name: Build with Buildozer in Docker
run: |
docker run --rm \
-v ${{ github.workspace }}:/home/user/app \
-w /home/user/app \
kivy/buildozer \
bash -lc "pip install --upgrade Cython==0.29.36 virtualenv && buildozer android debug"


- name: Upload APK artifact
uses: actions/upload-artifact@v4
with:
name: scicalc-apk
path: bin/*.apk
