name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.2.0
        env:
          USER: root            # <<< fix for "chown: invalid user: ‘user’"
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: scicalc-apk
          path: ${{ steps.buildozer.outputs.filename }}
