name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Buildozer composite action (handles SDK/NDK/Java setup internally)
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          # Stable Buildozer from PyPI
          buildozer_version: stable
          # Be explicit & verbose; 'android debug' produces an installable APK
          command: buildozer -v android debug

      # Upload the APK that the action tells us it generated
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: scicalc-apk
          path: ${{ steps.buildozer.outputs.filename }}

      # Always upload logs & Buildozer working dir for debugging if something goes wrong
      - name: Upload Buildozer logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-logs
          path: |
            .buildozer/android/platform/build-armeabi-v7a/*.log
            .buildozer/android/platform/build-arm64-v8a/*.log
            .buildozer/**/*.log
            .buildozer/**/*.txt
            .buildozer/**/*.json
            .buildozer/android/platform/build-*/dists/**/build*/outputs/**/*.apk
          if-no-files-found: ignore
