- name: Build with Buildozer
  id: buildozer
  uses: ArtemSBulgakov/buildozer-action@v1.2.0
  env:
    USER: root
    PIP_BREAK_SYSTEM_PACKAGES: "1"
    ANDROIDAPI: "34"     # <-- force target API 34 (was 31 in your log)
    ANDROIDMINAPI: "24"  # <-- force min SDK 24 (was 21 in your log)
  with:
    workdir: .
    buildozer_version: stable
    command: |
      python3 -m pip install --upgrade "cython==0.29.36" "setuptools<70" virtualenv || true
      # (optional) show versions for debugging
      python3 -V && pip -V
      buildozer -v android debug
