name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable BuildKit (fix image pull)
        run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

      - name: Cache Buildozer & Gradle
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            .gradle
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Pull Buildozer image manually
        run: docker pull kivy/buildozer:stable

      - name: Build with Buildozer in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            -w /home/user/app
